"""
agents/comms_agent.py

CommsAgent — reads final state and generates a weekly narrative report. Uses
the LLM for the summary; falls back to a deterministic template when offline.
Writes reports/WK<week>_summary.md.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from agents.base import BaseAgent
from guardrails import scrub

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"


class CommsAgent(BaseAgent):
    name = "CommsAgent"

    def _narrative(self, stats: dict) -> str:
        system = (
            "You are a content ops lead writing a concise internal weekly summary "
            "for a game streaming platform curation team. Be direct and factual. "
            "Max 3 short paragraphs."
        )
        user = (
            f"Week: {stats['week']} | Tier: {stats['tier']} | Region: {stats['region']}\n"
            f"Rows published: {stats['row_count']} | Total titles: {stats['total_titles']}\n"
            f"Publish status: {stats['publish_status']}\n"
            "Write the weekly summary."
        )
        text = self.llm(system=system, user=user, max_tokens=512)
        text = text or (
            f"Week {stats['week']} ({stats['tier']}/{stats['region']}) published "
            f"{stats['total_titles']} titles across {stats['row_count']} rows. "
            f"All gates passed; publish status {stats['publish_status']}."
        )
        # Output guardrail: redact PII / flag blocked terms before it leaves the pipeline.
        guarded = scrub(text)
        if guarded.redactions or guarded.flags:
            print(f"[CommsAgent] guardrail: {guarded.redactions} redaction(s), "
                  f"flags={guarded.flags}")
        return guarded.text

    def run(self, context: dict) -> str:
        rows = context["rows"]
        stats = {
            "week": context["week"],
            "tier": context["tier"],
            "region": context["region"],
            "row_count": len(rows),
            "total_titles": sum(len(v) for v in rows.values()),
            "publish_status": context.get("publish_status", "unknown"),
        }
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        rows_table = "\n".join(f"| {name} | {len(t)} |" for name, t in rows.items())
        md = f"""# Weekly Curation Summary — {stats['week']}

> Generated: {now} · Auto-generated by CommsAgent · NexCurate Multi-Agent Pipeline

## Overview

| Field | Value |
|-------|-------|
| Week | {stats['week']} |
| Tier | {stats['tier']} |
| Region | {stats['region']} |
| Rows | {stats['row_count']} |
| Total titles | {stats['total_titles']} |
| Publish status | {stats['publish_status']} |

## Row Breakdown

| Row | Title Count |
|-----|-------------|
{rows_table}

## Summary

{self._narrative(stats)}
"""
        REPORTS_DIR.mkdir(exist_ok=True)
        out = REPORTS_DIR / f"WK{stats['week']}_summary.md"
        out.write_text(md, encoding="utf-8")
        return str(out)
